- name: Add Microsoft APT KEY
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft repo
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/{{ansible_distribution_version}}/prod.list
    dest: /etc/apt/sources.list.d/mssql-release.list

- name: update apt cache
  apt: update_cache=yes

- name: install SQL Server dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - unixodbc-dev
    - msodbcsql17
  environment:
    ACCEPT_EULA: Y

- name: install SQL Server php modules
  pear: name={{ item }} 
  with_items:
   - pecl/sqlsrv
   - pecl/pdo_sqlsrv

- name: create SQL Server php configuration files
  template: src=../../../templates/php-mod.conf.j2 dest=/etc/php/{{system.php.version}}/mods-available/{{item}}.ini
  with_items:
    - sqlsrv
    - pdo_sqlsrv

- name: enable SQL Server php modules
  shell: phpenmod {{ item }} 
  with_items:
   - sqlsrv
   - pdo_sqlsrv

- name: restart php{{system.php.version}}-fpm
  service: name=php{{system.php.version}}-fpm enabled=yes state=restarted