- name: install MySQL
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
  - mysql-server
  - mysql-client
  - python3-mysqldb

- name: add ubuntu user
  mysql_user:
    name: ubuntu
    password: "vagrant"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present

- name: bind mysql remote address
  ini_file: dest=/etc/mysql/mysql.conf.d/mysqld.cnf
            section=mysqld
            option=bind-address
            value='0.0.0.0'

- name: restart mysql
  service: name=mysql enabled=yes state=restarted