---
- name: install MySQL
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
  - mysql-server
  - mysql-client
  - python-mysqldb
  register: mysql
  notify:
    - restart mysql

- name: add ubuntu user
  mysql_user:
    name: ubuntu
    password: "vagrant"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present

- name: bind mysql remote address
  ini_file: dest=/etc/my.cnf
            section=mysqld
            option=bind-address
            value='0.0.0.0'