- name: install MySQL
  apt:
    pkg:
      - mysql-server
      - mysql-client
      - python3-mysqldb
    state: latest
    update_cache: true

- name: add ubuntu user
  mysql_user:
    name: ubuntu
    password: "vagrant"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present

- name: bind mysql remote address
  ini_file: dest=/etc/mysql/mysql.conf.d/mysqld.cnf
            section=mysqld
            option=bind-address
            value='0.0.0.0'

- name: restart mysql
  service: name=mysql enabled=yes state=restarted