- name: install redis
  apt: name=redis-server state=latest

- name: allow redis remote connections
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    backrefs: yes
  with_items:
    - { regexp: '^bind 127.0.0.1', line: 'bind 0.0.0.0' }

- name: reload redis
  service: name=redis-server state=restarted
  