---

- name: update apt cache
  apt: update_cache=yes

- name: install system tools
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - build-essential
    - python-software-properties
    - bash-completion
    - vim
    - git
    - htop
    - imagemagick
    - mc
    - re2c
    - mcrypt
    - tree
    - ranger
    - optipng
    - pv

- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  changed_when: false

- name: configure timezone
  copy:
    content: "{{ system.timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 644
    backup: yes
  notify:
    - update timezone

- name: configure localtime
  file:
    src: /usr/share/zoneinfo/{{ system.timezone }}
    dest: /etc/localtime
    owner: root
    group: root
    mode: 644
    state: link
    force: yes
    backup: yes
  changed_when: false

- lineinfile: dest=/home/{{ ansible_user }}/.bashrc line='export LC_ALL="en_US.UTF-8"'
- lineinfile: dest=/home/{{ ansible_user }}/.bashrc line='export LANG="en_US.UTF-8"'

- name: install language packs
  apt: name=language-pack-en state=latest