- name: update apt cache
  apt: update_cache=yes

- name: install system tools
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - build-essential
    - bash-completion
    - vim
    - git
    - htop
    - mc
    - mcrypt
    - tree
    - pv
    - sqlite3
    - libsqlite3-dev
    - nginx
    - supervisor
    - beanstalkd
    - redis-server

- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  changed_when: false

- name: configure timezone
  copy:
    content: "{{ system.timezone }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 644
    backup: yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: configure localtime
  file:
    src: /usr/share/zoneinfo/{{ system.timezone }}
    dest: /etc/localtime
    owner: root
    group: root
    mode: 644
    state: link
    force: yes
    backup: yes
  changed_when: false

- name: install language packs
  apt: name=language-pack-en state=latest

- name: configure locale
  lineinfile: dest=/etc/default/locale line='{{item}}'
  with_items:
    - 'LANG="en_US.UTF-8"'
    - 'LC_ALL="en_US.UTF-8"'

- name: set supervisor to start on boot
  service: name=supervisor enabled=yes state=started

- name: bind beanstalkd remote address
  lineinfile: 
    dest: /etc/default/beanstalkd
    regexp: '^BEANSTALKD_LISTEN_ADDR'
    line: "BEANSTALKD_LISTEN_ADDR=0.0.0.0"

- name: reload beanstalkd
  service: name=redis-server state=restarted

- name: allow redis remote connections
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    backrefs: yes
  with_items:
    - { regexp: '^bind 127.0.0.1', line: 'bind 0.0.0.0' }

- name: reload redis
  service: name=redis-server state=restarted