- name: update apt cache
  apt: update_cache=yes

- name: install system tools
  apt:
    pkg:
      - curl
      - wget
      - build-essential
      - bash-completion
      - vim
      - htop
      - mc
      - mcrypt
      - tree
      - pv
      - sqlite3
      - libsqlite3-dev
      - language-pack-en
      - ntpdate
      - chrony
      - supervisor
      - beanstalkd
      - redis-server
    state: latest

- name: set services to start on boot
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - supervisor
    - beanstalkd
    - redis-server

- name: install nginx
  apt: name=nginx state=latest
  when: system.web_server == 'nginx'

- name: install apache2
  apt: name=apache2 state=latest
  when: system.web_server == 'apache2'

- name: enable apache modules
  apache2_module: state=present name={{ item }}
  with_items:
    - rewrite
    - ssl
    - actions
  when: system.web_server == 'apache2'

- name: restart apache
  service: name=apache2 enabled=yes state=restarted
  when: system.web_server == 'apache2'

- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  changed_when: false

- name: configure localtime
  file:
    src: /usr/share/zoneinfo/{{ system.timezone }}
    dest: /etc/localtime
    owner: root
    group: root
    mode: 644
    state: link
    force: yes
  register: server_timezone

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: server_timezone.changed

- name: configure locale
  lineinfile:
    dest: /etc/default/locale
    line: "{{ item.line }}"
  with_items:
    - { line: 'LANG="en_US.UTF-8"' }
    - { line: 'LC_ALL="en_US.UTF-8"' }

- name: update beanstalkd configuration
  lineinfile:
    dest: /etc/default/beanstalkd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^BEANSTALKD_LISTEN_ADDR', line: 'BEANSTALKD_LISTEN_ADDR=0.0.0.0' }

- name: update redis configuration
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^bind 127.0.0.1', line: 'bind 0.0.0.0' }

- name: restart services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - supervisor
    - beanstalkd
    - redis-server
