- name: install java
  apt: name=openjdk-8-jre state=latest

- name: install elasticsearch
  apt:
    deb: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.deb"

- name: just force systemd to reread configs
  systemd: daemon_reload=yes

- name: tweak jvm.options configuration
  lineinfile: 
    dest: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    backrefs: yes
  with_items:
    - { regexp: '^-Xms1g', line: '-Xms128m' }
    - { regexp: '^-Xmx1g', line: '-Xmx128m' }

- name: restart elasticsearch
  service: name=elasticsearch enabled=yes state=restarted