- name: install java
  apt: name=openjdk-8-jre state=latest

- include_tasks: "elasticsearch-{{ system.elasticsearch_version }}.yaml"

- name: restart elasticsearch
  service: name=elasticsearch enabled=yes state=restarted