- apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: 'yes'

- name: install php{{system.php.version}} extensions
  apt:
    pkg: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    prefix: "php{{system.php.version}}-"
    packages: "{{ [prefix] | product(system.php.extensions) | map('join') | list }}"  

- name: install apache php-mod
  apt: name=libapache2-mod-php{{system.php.version}} state=latest
  when: system.web_server == 'apache2'

- name: tweak php.ini configuration (cli)
  lineinfile:
    dest: /etc/php/{{ system.php.version }}/cli/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    backrefs: yes
  with_items:
    - { regexp: '^max_execution_time =', line: 'max_execution_time = 600' }
    - { regexp: '^memory_limit =', line: 'memory_limit = 1024M' }
    - { regexp: '^error_reporting =', line: 'error_reporting = E_ALL' }
    - { regexp: '^display_errors =', line: 'display_errors = On' }
    - { regexp: '^display_startup_errors', line: 'display_startup_errors = On' }
    - { regexp: '^post_max_size =', line: 'post_max_size = 128M' }
    - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = 128M' }
    - { regexp: '^;cgi.fix_pathinfo', line: 'cgi.fix_pathinfo = 0' }
    - { regexp: '^allow_url_fopen', line: 'allow_url_fopen = On' }

- name: tweak php.ini configuration (fpm)
  lineinfile:
    dest: /etc/php/{{ system.php.version }}/fpm/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
    backrefs: yes
  with_items:
    - { regexp: '^max_execution_time =', line: 'max_execution_time = 600' }
    - { regexp: '^memory_limit =', line: 'memory_limit = 1024M' }
    - { regexp: '^error_reporting =', line: 'error_reporting = E_ALL' }
    - { regexp: '^display_errors =', line: 'display_errors = On' }
    - { regexp: '^display_startup_errors', line: 'display_startup_errors = On' }
    - { regexp: '^post_max_size =', line: 'post_max_size = 128M' }
    - { regexp: '^upload_max_filesize', line: 'upload_max_filesize = 128M' }
    - { regexp: '^;cgi.fix_pathinfo', line: 'cgi.fix_pathinfo = 0' }
    - { regexp: '^allow_url_fopen', line: 'allow_url_fopen = On' }

- name: set php{{ system.php.version}} as default
  command: update-alternatives --set php /usr/bin/php{{ system.php.version}}
  changed_when: false

- name: restart php{{system.php.version}}-fpm
  service: name=php{{system.php.version}}-fpm enabled=yes state=restarted
