- name: install php7.0-fpm
  apt:
    pkg:
      - php7.0-fpm
      - php7.0-cli
      - php7.0-mysql
      - php7.0-curl
      - php7.0-mcrypt
      - php7.0-mbstring
      - php7.0-common
      - php7.0-gd
      - php7.0-soap
      - php7.0-zip
      - php7.0-bcmath
      - php7.0-xml
      - php7.0-sqlite3
      - php7.0-dev
      - php7.0-odbc
    state: latest
    update_cache: true