- name: install php7.3-fpm
  apt:
    pkg:
      - php7.3-fpm
      - php7.3-cli
      - php7.3-mysql
      - php7.3-curl
      - php7.3-mbstring
      - php7.3-common
      - php7.3-gd
      - php7.3-soap
      - php7.3-zip
      - php7.3-bcmath
      - php7.3-xml
      - php7.3-sqlite3
      - php7.3-dev
      - php7.3-odbc
    state: latest
    update_cache: true