- name: create vhosts certificates
  include_tasks: ssl.yml
  when: vhost.ssl
  loop_control:
    loop_var: vhost
  with_items: "{{ vhosts }}"

- name: create vhosts
  include_tasks: vhost.yml
  loop_control:
    loop_var: vhost
  with_items: "{{ vhosts }}"

- name: restart {{system.web_server}}
  service: name={{system.web_server}} enabled=yes state=restarted

- name: reload supervisor
  service: name=supervisor state=restarted