- name: copy virtual hosts
  template: src=../templates/vhosts.conf.j2 dest=/etc/nginx/sites-available/{{item.name}}
  with_items: "{{ vhosts }}"

- name: create vhost simlink
  file: path=/etc/nginx/sites-enabled/{{item.name}}
        src=/etc/nginx/sites-available/{{item.name}}
        state=link
        force=yes
  with_items: "{{ vhosts }}"

- name: reload nginx
  service: name=nginx enabled=yes state=restarted

- name: create /etc/hosts entries
  lineinfile: 
    dest: /etc/hosts
    line: "127.0.0.1    {{ item.server_name }}"
    state: present
  with_items: "{{ vhosts }}"

- name: enable supervisor config
  template: src=../templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{item.name}}.conf
  with_items: "{{ vhosts }}"
  when: item.supervisor.commands is defined

- name: reload supervisor
  service: name=supervisor state=restarted