- include_tasks: "{{ system.web_server }}.yml"

- name: create /etc/hosts entries
  lineinfile: 
    dest: /etc/hosts
    line: "127.0.0.1    {{ item.server_name }}"
    state: present
  with_items: "{{ vhosts }}"

- name: enable supervisor config
  template: src=../templates/supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{item.name}}.conf
  with_items: "{{ vhosts }}"
  when: item.supervisor is defined and item.supervisor.commands is defined

- name: reload supervisor
  service: name=supervisor state=restarted