- name: copy virtual hosts
  template: src=../templates/nginx-vhost.conf.j2 dest=/etc/nginx/sites-available/{{item.name}}
  with_items: "{{ vhosts }}"

- name: create vhost simlink
  file: path=/etc/nginx/sites-enabled/{{item.name}}
        src=/etc/nginx/sites-available/{{item.name}}
        state=link
        force=yes
  with_items: "{{ vhosts }}"

- name: reload nginx
  service: name=nginx enabled=yes state=restarted